### PR TITLE
Remove dependency on nose, fixes #17

### LINKED ISSUE #17: remove nose
Hi,

could you please consider to remove dependency on deprecated nose? Tests run just fine with pytest for example.

### PR DESCRIPTION
**Pull request by sbraz**
Hi, this won't fix Travis CI but it should be enough for tests to pass without nose installed.

### CODE REVIEW

**Comment by Fuuzetsu** [comment]
I'd say this project is dead but sure, I can hit merge at the very least...

**Comment by sbraz** [comment]
We still package it at Gentoo and apparently openSUSE does too :) https://repology.org/project/torrentinfo/versions
Thanks for the merges!

**Comment by Fuuzetsu** [comment]
Right: it might be worth not packaging it anymore after some point. There are AFAIU many tools that have pretty much the same functionality (or more)! I don't think portage has any usage metrics but I doubt anyone would really miss this...

Up to you :shrug:

**Comment by sbraz** [comment]
I tried looking for alternatives but I couldn't find anything lightweight enough, do you have any suggestions.

**Comment by Fuuzetsu** [comment]
> I tried looking for alternatives but I couldn't find anything lightweight enough, do you have any suggestions.

Depends on your definition of lightweight: build dependencies? LOC? runtime dependencies?. Bunch of things at https://unix.stackexchange.com/questions/31486/is-there-a-tool-to-view-a-torrent-file .

**Pull request merged**
